### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by jbreindl** [alelab-upenn/ros-net-sim#2]
I attempted to install this project as per the instructions in the `README` but I'm faced with the following output from catkin (screenshot was taken after my first install attempt but the output roughly matches the first time I ran the commands).
![catkin issue](https://user-images.githubusercontent.com/47394530/129923832-905354c2-57a8-4fe7-af04-96e77cc4cf2e.png)

**Comment by slamlixiaodong** [comment]
when I launch the example.launch in the patrol_example branch, I find two robot is not Spawned. But I used empty.launch in gazebo, two robot can be Spawned, and show me rostopic message. Are you doing some experience about this?
