### ISSUE TITLE
How to download WINTERsim software?

### ISSUE THREAD

**Issue by YUJX19** [alelab-upenn/ros-net-sim#4]
I looked for **WINTERsim** online, but it turned out to be a **CARLA Simulator** of Winter, not the network simulator. Moreover, The software [download website](https://winter-group.net/download/)  mentioned in the paper can't open, and I only get the reply, "The requested URL was not found on this server was returned."

**Comment by slamlixiaodong** [comment]
when I launch the example.launch in the patrol_example branch, I find two robot is not Spawned. But I used empty.launch in gazebo, two robot can be Spawned, and show me rostopic message. Are you doing some experience about this?

**Comment by slamlixiaodong** [comment]
> 
http://winter-group.net/download/

**Comment by zhangteng0526** [comment]
I would like to ask whether the two brothers have built a co-simulation platform according to rosnetsim. Could you please communicate with me? Thank you here
